apiVersion: v1
kind: Pod
metadata:
  name: nginx-pv
spec:
  containers:
    - name: nginx-pv
      image: nginx
      volumeMounts:
        - mountPath: "/var/www/html"
          name: npv
  volumes:
    - name: npv
      persistentVolumeClaim:
        claimName: my-manual-claim
  #nodeSelector:
  #  name: nginx
