kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: my-manual-claim2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: mongo
  selector:
    matchLabels:
      name: mongo
