---

- name: Install PHP
  apt:
    name: php5=5.6.*
    #force: yes
    state: installed

- name: Install php related libraries and php5-fpm
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - php5-cli
    - php5-curl
    - php5-mysql
    - php5-mcrypt
    - php5-fpm

- name: Copy php.ini, php-fpm.conf and www.conf template files
  template: src=php.ini dest=/etc/php5/fpm/php.ini
- name: Copy php.ini, php-fpm.conf and www.conf template files
  template: src=php-fpm.conf dest=/etc/php5/fpm/php-fpm.conf
- name: Copy php.ini, php-fpm.conf and www.conf template files
  template: src=www.conf dest=/etc/php5/fpm/pool.d/www.conf

- name: start php-fpm service and enable
  service:
    name: php5-fpm
    state: restarted
    enabled: yes



