apiVersion: v1
kind: Pod
metadata:
  labels:
    app: redis-cli
  name: redis-cli
spec:
  containers:
    - name: redis-cli
      image: redis:4.0.8
      command: ["redis-server"]
      volumeMounts:
        - mountPath: /data
          name: data
  volumes:
    - name: data
      emptyDir: {}
