---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
  labels:
    name: jenkins
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    name: jenkins

