apiVersion: v1
kind: ConfigMap
metadata:
  name: saas-pulse-sp
  labels:
    app: saas-pulse-sp
    group: sp
    ms: saas
data:
  HAA_application_id: "saas-pulse-sp"
  HAA_state_dir: "/mnt/data/pulse"
  HAA_source_events_topic_name: "haa-harman-dev-events"
  HAA_source_alerts_topic_name: "haa-harman-dev-alerts"
  HAA_source_haaInternal_topic_name: "haa-harman-dev-haa-internal"
  HAA_sink_notification_topic_name: "haa-harman-dev-alerts-pulse"
  HAA_sink_dl_topic_name: "haa-harman-dev-dead-letters"
  HAA_pulse_halt_to_complete_transition_duration_ms: "300000"
  HAA_pulse_imputation_duration_ms: "300000"
  HAA_db_name: "ignite"
  HAA_poll_ms: "100"
  MALLOC_ARENA_MAX: "8"
  HAA_consumer_max_poll_records: "1000"
  HAA_max_poll_records: "1000"
  HAA_producer_linger_ms: "500"
  HAA_producer_batch_size: "32768"
  HAA_consumer_request_timeout_ms: "305000"
  HAA_request_timeout_ms: "305000"
  HAA_session_timeout_ms: "300000"
  HAA_consumer_session_timeout_ms: "300000"
  HAA_max_poll_interval_ms: "600000"
  HAA_consumer_max_poll_interval_ms: "600000"
  HAA_num_stream_threads: "1"
  HAA_auto_offset_reset: "earliest"
  HAA_bootstrap_servers: "kafka-0.kafka-svc.default.svc.cluster.local:9092,kafka-1.kafka-svc.default.svc.cluster.local:9092,kafka-2.kafka-svc.default.svc.cluster.local:9092"
  HAA_zookeeper_connect: "zk-0.zk-svc.default.svc.cluster.local:2182,zk-1.zk-svc.default.svc.cluster.local:2182,zk-2.zk-svc.default.svc.cluster.local:2182"
  LOG_LEVEL: "-DLOG_LEVEL=DEBUG"
  LOG_FILE_LOCATION: "-DLOG_FILE_LOCATION=/mnt/logs/saas/pulse-sp/pulse.log"
  HAA_kafka_ssl_enable: "false"
  HAA_metric_reporters_name: ""
  HAA_metric_logging_interval: "3600"
  JVM_OPTS: "-Xmx1g -Xms1g -XX:NativeMemoryTracking=detail -XX:MetaspaceSize=96m -XX:G1HeapRegionSize=16M -XX:MinMetaspaceFreeRatio=50 -XX:MaxMetaspaceFreeRatio=80 -server -XX:+UseG1GC -XX:MaxGCPauseMillis=20 -XX:InitiatingHeapOccupancyPercent=35 -XX:+DisableExplicitGC -Djava.awt.headless=true"
---
apiVersion: v1
kind: Service
metadata:
  name: saas-pulse-sp-svc
  labels:
    app: saas-pulse-sp
spec:
  ports:
  - port: 1883
    name: server
  clusterIP: None
  selector:
    app: saas-pulse-sp
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: saas-pulse-sp
spec:
  serviceName: saas-pulse-sp-svc
  selector:
    matchLabels:
      app: saas-pulse-sp
  replicas: 2
  template:
    metadata:
      labels:
        app: saas-pulse-sp
        group: sp
        ms: saas
      name: saas-pulse-sp
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node.ignite.harman.com/component
                operator: In
                values: ["streaming"]
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - saas-pulse-sp
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: saas-pulse-sp
        image: registry.ahanet.net:5000/haa/haa-pulse2:8.2-SNAPSHOT
        imagePullPolicy: Always
        command: 
        - sh
        - -c
        - "/bin/sh /haa-pulse2/bin/start.sh"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
        envFrom:
        - configMapRef:
            name: saas-pulse-sp
        volumeMounts:
          - mountPath: /mnt/data/saas/pulse-sp
            name: saas-pulse-sp-data
          - mountPath: /mnt/logs/saas/pulse-sp
            name: saas-pulse-sp-logs
      volumes:
        - name: saas-pulse-sp-logs
          emptyDir: {}
      imagePullSecrets:
      - name: regcred
  volumeClaimTemplates:
  - metadata:
      name: saas-pulse-sp-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: normal
      resources:
        requests:
          storage: 100Gi
