apiVersion: v1
kind: Service
metadata:
  name: php-fpm
  labels:
    name: php-fpm
spec:
    type: ClusterIP
    ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
    selector:
      name: php-fpm


