---

#- name: disable selinux
    #command: /sbin/setenforce 0
    # or
    #shell: /sbin/setenforce 0
    #ignore_errors: True

- name: create user 'apache' if not exists
  user:
    name: apache
    comment: "Apache User"
    createhome: no
    password: no

- name: create user 'centos' if not exists
  user:
    name: centos
    comment: "centos user"

- name: Add centos and apache users to /etc/sudoers file
  lineinfile:
    path: /etc/sudoers
    backup: yes
    #line: '%centos ALL=(ALL) NOPASSWD: ALL\n%apache ALL=(ALL) NOPASSWD: ALL'
    line: "{{ item }}"
    insertafter: '^root'
  with_items:
    - '%centos ALL=(ALL) NOPASSWD: ALL'
    - '%apache ALL=(ALL) NOPASSWD: ALL'

- name: create directories /apps/nginx/html and /apps/nginx/logs/default if not exists

  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: root
    group: root
  with_items:
    - /apps/nginx/html
    - /apps/nginx/logs/default
    - /apps/php-fpm/logs
    - /etc/nginx/conf.d


- name: Install common packages
  yum: name={{ item }} update_cache=yes state=present
  with_items:
    - git
    - jq
    - curl
    - wget
    - policycoreutils
    - policycoreutils-python
    - selinux-policy
    - selinux-policy-targeted
    - libselinux-utils
    - setroubleshoot-server
    - setools
    - setools-console
    - mcstrans

#- name: enable epel repo
#  yum_repository:
#    name: epel
#    description: yum EPEL repo
#    mirrorlist: https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch
#    enabled: yes

- name: remi repo
  yum_repository:
    file: remi
    name: remi
    description: yum REMI repo
    mirrorlist: http://rpms.remirepo.net/enterprise/7/remi/mirror
    enabled: yes
    gpgcheck: yes
    gpgkey: https://rpms.remirepo.net/RPM-GPG-KEY-remi

- name: remi repo for php 5.6
  yum_repository:
    file: remi
    name: remi-php56
    description: yum REMI repo for php 5.6
    mirrorlist: http://rpms.remirepo.net/enterprise/7/php56/mirror
    enabled: yes
    gpgcheck: yes
    gpgkey: https://rpms.remirepo.net/RPM-GPG-KEY-remi

- name: clean all yum cache
  command: yum clean all
  register: php_repo_added

- debug: msg="changed"
  when: php_repo_added.changed










