---
kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  ports:
  - port: 9200
    name: "9200"
    protocol: TCP
  - port: 9300
    name: "9300"
    protocol: TCP
  clusterIP: None

---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: elasticsearch
spec:
  serviceName: elasticsearch
  selector:
    matchLabels:
      app: elasticsearch
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch
      name: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: elasticsearch:2
        command: ["elasticsearch"]
        args: ["-Des.cluster.name='graylog'", "-Des.insecure.allow.root=true"]
        imagePullPolicy: Always
        ports:
          - containerPort: 9200
          - containerPort: 9300
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: elasticsearch
  volumeClaimTemplates:
  - metadata:
      name: elasticsearch
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: normal
      resources:
        requests:
          storage: 100Gi



