---
kind: Service
apiVersion: v1
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  selector:
    app: mongo
  ports:
  - port: 27017
    protocol: TCP
  clusterIP: None

---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: mongo
spec:
  serviceName: mongo
  selector:
    matchLabels:
      app: mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
      name: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:3
        imagePullPolicy: Always
        ports:
        - containerPort: 27017
        volumeMounts:
        - mountPath: /data/db
          name: mongo
  volumeClaimTemplates:
  - metadata:
      name: mongo
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: normal
      resources:
        requests:
          storage: 30Gi



