---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: graylog-nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-graylog
        image: jp19214/nginx:new
        imagePullPolicy: Always
        ports:
        - containerPort: 80

