---

- name: Install the selinux python module
  package: name={{ item }} state=present
  with_items:
    - libselinux-python
    - libsemanage-python
  when: ansible_os_family == "RedHat"

- name: Set SELinux boolean to allow nginx
  command: semanage permissive -a httpd_t 

- name: NGINX | Installing NGINX
  yum:
    name: 'roles/nginx/files/nginx-1.8.0-1.el7.ngx.x86_64.rpm'
    #name: nginx=1.8.*
    update_cache: yes
    state: installed
 
- name: NGINX | copying template nginx.conf
  #template: src= "{{ item.src }}" dest= "{{ item.dest }}"
  #with_items: 
  #  - { src: 'nginx.conf', dest: '/etc/nginx/nginx.conf' }
  #  - { src: 'default.conf', dest: '/etc/nginx/conf.d/default.conf' }
  template: src='nginx.conf' dest='/etc/nginx/nginx.conf'
- name: NGINX | copying template default.conf
  template: src='default.conf' dest='/etc/nginx/conf.d/default.conf'

- name: Nginx logs permissions
  file:
    path: '/apps/nginx/logs/'
    state: directory
    recurse: yes
    mode: 0766

- name: NGINX | Starting NGINX
  service: name=nginx state=restarted enabled=yes
  
  #notify: 
  #- restart nginx

